name: robot-tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        run: |
          mkdir -p reports
          robot --outputdir reports tests/

      - name: Upload Robot Report
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: reports/*
          retention-days: 7
